name: Build cs4215-jikun-kaian.github.io
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy cs4215-jikun-kaian.github.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies (apt)
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
          libxi-dev libgl1-mesa-dev
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - id: get-time
        run: echo "time=$(date -Iseconds)" >> $GITHUB_OUTPUT
      - name: yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn run build
        env:
          REACT_APP_PLAYGROUND_ONLY: 'TRUE'
          REACT_APP_VERSION: ${{ format('{0}-{1}', github.sha, steps.get-time.outputs.time) }}
          REACT_APP_ENVIRONMENT: 'pages'
          PUBLIC_URL: 'https://cs4215-jikun-kaian.github.io'
      - name: Remove sourcemaps
        working-directory: build
        run: |
          find -name '*.map' -print -delete
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: CS4215-Jikun-Kaian/cs4215-jikun-kaian.github.io
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_dir: ./build
          publish_branch: master
          force_orphan: true
